[tool.poetry]
name = "openmunge"
version = "0.1.0"
description = ""
authors = ["Jeremy Rempel <jdrempel@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

